export const SELECT_NOOTROPIC = 'SELECT_NOOTROPIC';
export const SELECT_NOOTROPICS = 'SELECT_NOOTROPICS';
export const INSERT_NOOTROPIC = 'INSERT_NOOTROPIC';
export const UPDATE_NOOTROPIC = 'UPDATE_NOOTROPIC';
export const DELETE_NOOTROPIC = 'DELETE_NOOTROPIC';
