export const SELECT_DAILY_FOOD = 'SELECT_DAILY_FOOD';
export const SELECT_DAILY_FOODS = 'SELECT_DAILY_FOODS';
export const SELECT_DAILY_FOOD_CATEGORIES = 'SELECT_DAILY_FOOD_CATEGORIES';
export const INSERT_DAILY_FOOD = 'INSERT_DAILY_FOOD';
export const UPDATE_DAILY_FOOD = 'UPDATE_DAILY_FOOD';
export const DELETE_DAILY_FOOD = 'DELETE_DAILY_FOOD';
