export const SELECT_VITAMIN = 'SELECT_VITAMIN';
export const SELECT_VITAMINS = 'SELECT_VITAMINS';
export const INSERT_VITAMIN = 'INSERT_VITAMIN';
export const UPDATE_VITAMIN = 'UPDATE_VITAMIN';
export const DELETE_VITAMIN = 'DELETE_VITAMIN';
