export const SELECT_TOBACCO = 'SELECT_TOBACCO';
export const SELECT_TOBACCOS = 'SELECT_TOBACCOS';
export const INSERT_TOBACCO = 'INSERT_TOBACCO';
export const UPDATE_TOBACCO = 'UPDATE_TOBACCO';
export const DELETE_TOBACCO = 'DELETE_TOBACCO';
