export const SELECT_MEDICINE = 'SELECT_MEDICINE';
export const SELECT_MEDICINES = 'SELECT_MEDICINES';
export const INSERT_MEDICINE = 'INSERT_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
